workspace/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SelectField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from workspace.models import User

#The form to post space to the database
class PostForm(FlaskForm):
    choices = [('Nigeria', 'Nigeria'), ('Argentina', 'Argentina'), 
    ('Algeria', 'Algeria'), ('Benin', 'Benin'),('Brazil', 'Brazil'), 
    ('Cuba', 'Cuba'),('United States', 'United States'),('United Kingdom', 'United Kingdom'),
    ('Togo', 'Togo'),('South Africa', 'South Africa'),('Portugal', 'Portugal')
    ]
    country = SelectField('Select a Country', choices=choices)
    title = StringField('Title', validators=[DataRequired()])
    image = FileField('Upload Picture', validators=[FileAllowed(['jpg', 'png'])])
    size = StringField('Size', validators=[DataRequired()])
    location = StringField('Location', validators=[DataRequired()])
    price = StringField('Price', validators=[DataRequired()])
    space_type = StringField('Space Type', validators=[DataRequired()])
    availability = StringField('Availability', validators=[DataRequired()])
    facility = TextAreaField('Facility', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    contact = TextAreaField('Contact', validators=[DataRequired()])
    submit = SubmitField('Post')

#The form to Search space from the database
class SearchForm(FlaskForm):
    choices = [('Nigeria', 'Nigeria'), ('Argentina', 'Argentina'), 
    ('Algeria', 'Algeria'), ('Benin', 'Benin'),('Brazil', 'Brazil'), 
    ('Cuba', 'Cuba'),('United States', 'United States'),('United Kingdom', 'United Kingdom'),
    ('Togo', 'Togo'),('South Africa', 'South Africa'),('Portugal', 'Portugal')]
    country = SelectField('Select a Country', choices=choices)
    submit = SubmitField('Post')

workspace/main/routes.py
from flask import render_template, request, Blueprint
from workspace.models import Post

main = Blueprint('main', __name__)
"""
This is the first page loaded by the browser,
It load with the space post available in the database 
it and redirect to home page when Home is click
"""
@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route("/about")
def about():
	#Route to redirect to about page when about is click or enter into the browser address
    return render_template('about.html', title='About')


@main.route("/contact")
def contact():
	#Route to redirect to Contact page when contact is click or enter into the browser address
    return render_template('contact.html', title='Contact')

workspace/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from workspace import db, bcrypt
from workspace.models import User, Post
from workspace.posts.forms import PostForm
from workspace.posts.utils import save_picture

posts = Blueprint('posts', __name__)

#Route to submit the post form and redirect back to create post
@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        if form.image.data:
            image_file = save_picture(form.image.data)
            
        post = Post(title=form.title.data, description=form.description.data, size=form.size.data, location=form.location.data, country=form.country.data, image = image_file, price=form.price.data, space_type=form.space_type.data, availability=form.availability.data, facility=form.facility.data, contact=form.contact.data,  author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')

#Route to view space post by the ID
@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

#Route to edit space post by the ID
@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')

#Route to delete space post by the ID
@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

@posts.route('/post/search', methods=['GET'])
def search():
    selected_country = request.args.get('country')
    if selected_country:
        posts = Post.query.filter_by(country=selected_country).all()
    else:
        posts = []
    return render_template('search_results.html', posts=posts)

workspace/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from workspace import db, bcrypt
from workspace.models import User, Post
from workspace.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from workspace.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

workspace/templates/about.html
<!--
	A page where everything about Workspace is writen
-->
{% extends "layout.html" %}
{% block content %}
<div class="col-md-12 topbar content" >
    <center><h2 style=" color: white;">About WorkSpace</h2></center>
	<p> 
		WorkSpace is a
		<a href="https://intranet.alxswe.com" target="_blank" style=" text-decoration: none; color: purple;"> Portfolio Project for Holberton School </a>that deals with
		the difficulty of getting an Office space for short-term needs like in one, two, three or six months to work with your team is always an issue This scenario is common for startups, remote teams, and professionals who need temporary workspace when relocating or during specific projects.<br> The challenges they encounter are:<br>
				<b>Availability and Location:</b> Finding vacant office space that matches your requirements in terms of size, amenities, and location can be challenging, especially in popular business districts.<br>
				<b>Cost and Budget:</b> Traditional office leases typically require longer commitments and might not be cost-effective for short-term needs.<br>
				<b>Infrastructure and Setup:</b> Setting up the necessary infrastructure (internet, utilities, furniture, etc.) for a short-term office can be time-consuming and costly.
				Booking and Availability: Depending on demand, short-term spaces might not always be available when you need them.<br>
	</p>
	<center><h2 style=" color: white;">What We Offer</h2></center>
	<p>
		It is a website where startups, remote teams, and professionals who need temporary workspace at any location when relocating or during specific projects will have Office Space for rent that matches their requirements in terms of size, amenities, and location, where necessary infrastructure (internet, utilities, furniture, etc.) will be made available and cost-effective, and Booking will be Available at all times. It is a site where anybody can post Office space from any location all over the world, not just certain places or countries.
	</p>
</div>
{% endblock content %}

workspace/templates/account.html
<!--
    A page that loads base on the account loged in
-->
{% extends "layout.html" %}
{% block content %}
    <div class="content-section topbar">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

workspace/templates/home.html
<!--
  The host page that loads all space posted from the database.
-->
{% extends "layout.html" %}
{% block content %}
<div class="col-md-12" >
    <div class="bannar">
  <div class="top">
    <center>
      <h1 style="color: white;">Welcome to WorkSpace</h1>
      <h3 style="color: white;">Where Working AnyWhere is Possible</h3>
      <a href="{{ url_for('main.about') }}" target="_blank"class="btn btn-primary me-md-2">More Details</a>
    </center>
  </div>
</div>
</div>

  <div class="col-md-12" style=" color: white; text-align: center; font-weight: bolder;">
    <h2 style=" color: white; font-weight: bolder;">LOOKING FOR YOUR NEXT WORKSPACE?</h2>

<p>We make moving in quick and easy. Enquire today and you could be in your new space within a month.</p>
  </div>
  <div class="col-5 search" style="">
    <form method="GET" action="/post/search">
    <label for="country">Search by Location:</label>
    <select id="country" name="country">
        <option value="Nigeria">Nigeria</option>
        <option value="Argentina">Argentina</option>
        <option value="Algeria">Algeria</option>
        <option value="Benin">Benin</option>
        <option value="Brazil">Brazil</option>
        <option value="Cuba">Cuba</option>
        <option value="United States">United States</option>
        <option value="United Kingdom">United Kingdom</option>
        <option value="Togo">Togo</option>
        <option value="South Africa">South Africa</option>
        <option value="Portugal">Portugal</option>
        <!-- Add more country options here -->
    </select>
    <input type="submit" value="Search">
</form>
</div>
<div style=" clear: both;"></div>
<div class="row">
    {% for post in posts.items %}
    <div class="col-4">
        <article class="media content-section" >
          
          <div class="media-body">
            
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <img class="space-img" src="{{ url_for('static', filename='space_image/' + post.image) }}">
            <p class="article-content">${{ post.price }}</p>
            <p class="article-content">{{ post.location }}</p>
            <p class="article-content">{{ post.country }}</p>
            <p class="article-content">{{ post.description }}</p>
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
          
        </article>
      </div>
    {% endfor %}
    </div>
    <div style=" clear: both;"></div>
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

workspace/templates/layout.html
<!--
  This is the top part of every page been loaded
-->
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
     <link rel="shortcut icon" href="{{ url_for('static', filename='icon.png') }}" >

    {% if title %}
        <title>WorkSpace - {{ title }}</title>
    {% else %}
        <title>WorkSpace</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/"><img src="{{ url_for('static', filename='logo1.png') }}" alt="WorkSpace"> </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
              <a class="nav-item nav-link" href="{{ url_for('main.contact') }}">Contact</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container" style=" width: 100%">
      <div class="row">
        <div class="container" >
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>

      </div>
    </main>
<hr style=" background-color: white;">
<footer id="footer">
<p>Web Developerment by Oluwaseun and Jamil</p>
<p>Icons by <a target="_blank" href="https://icons8.com">Icons8</a></p> 
</footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

workspace/templates/login.html
<!--
    A page that contain the form to sign In
-->
{% extends "layout.html" %}
{% block content %}
    <div class="content-section topbar">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

workspace/templates/post.html
<!--
  A page that contain all details of a posted space according to the ID
-->
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section topbar">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <img class="space-img" src="{{ url_for('static', filename='space_image/' + post.image) }}">
  <p class="article-content">Price: ${{ post.price}}</p>
      <p class="article-content">Address: {{ post.location }}</p>
      <p class="article-content">Location: {{ post.country }}</p>
      <p class="article-content">Size: {{ post.size }}</p>
      <p class="article-content">Type: {{ post.space_type }}</p>
      <p class="article-content">Space Size: {{ post.accommodation_size }}</p>
      <p class="article-content">Facilities: {{ post.facility }}</p>
      <p class="article-content">Availability: {{ post.availability }}</p>
      <p class="article-content">Description: {{ post.description }}</p>
      <p class="article-content">Contact: {{ post.contact }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

workspace/templates/search_results.html
<!--
  A page that contain all details of a posted space according to your search
-->
{% extends "layout.html" %}
{% block content %}
{% for post in posts %}
  <article class="media content-section topbar">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>      
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <img class="space-img" src="{{ url_for('static', filename='space_image/' + post.image) }}">
  <p class="article-content">Price: ${{ post.price}}</p>
      <p class="article-content">Address: {{ post.location }}</p>
      <p class="article-content">Location: {{ post.country }}</p>
      <p class="article-content">Size: {{ post.size }}</p>
      <p class="article-content">Type: {{ post.space_type }}</p>
      <p class="article-content">Space Size: {{ post.accommodation_size }}</p>
      <p class="article-content">Facilities: {{ post.facility }}</p>
      <p class="article-content">Availability: {{ post.availability }}</p>
      <p class="article-content">Description: {{ post.description }}</p>
      <p class="article-content">Contact: {{ post.contact }}</p>
    </div>
  </article>
{% endfor %}
{% endblock content %}

workspace/templates/user_posts.html
<!--
  A page that contain the space posted by a user
-->
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section topbar">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <img class="space-img" src="{{ url_for('static', filename='space_image/' + post.image) }}">
  <p class="article-content">{{ post.price}}</p>
      <p class="article-content">{{ post.location }}</p>
      <p class="article-content">{{ post.country }}</p>
      <p class="article-content">{{ post.size }}</p>
      <p class="article-content">{{ post.space_type }}</p>
      <p class="article-content">{{ post.accommodation_size }}</p>
      <p class="article-content">{{ post.facility }}</p>
      <p class="article-content">{{ post.accommodation_size }}</p>
      <p class="article-content">{{ post.availability }}</p>
      <p class="article-content">{{ post.description }}</p>
      <p class="article-content">{{ post.contact }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}